/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package de.whitewashing.php.cs;

import org.openide.util.NbPreferences;

final class CodeSnifferPanel extends javax.swing.JPanel {

    private final CodeSnifferOptionsPanelController controller;

    CodeSnifferPanel(CodeSnifferOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStandard = new javax.swing.JLabel();
        checkBoxShowWarnings = new javax.swing.JCheckBox();
        inputBoxStandard = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(labelStandard, org.openide.util.NbBundle.getMessage(CodeSnifferPanel.class, "CodeSnifferPanel.labelStandard.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(checkBoxShowWarnings, org.openide.util.NbBundle.getMessage(CodeSnifferPanel.class, "CodeSnifferPanel.checkBoxShowWarnings.text")); // NOI18N

        inputBoxStandard.setEditable(true);
        inputBoxStandard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zend", "PEAR", "PHPCS", "Squiz", "MySource" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(labelStandard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxShowWarnings)
                    .addComponent(inputBoxStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStandard)
                    .addComponent(inputBoxStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(checkBoxShowWarnings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        inputBoxStandard.setSelectedItem(
                NbPreferences.forModule(CodeSniffer.class).get("phpcs.codingStandard", "Zend")
                );

        checkBoxShowWarnings.setSelected(
                NbPreferences.forModule(CodeSniffer.class).getBoolean("phpcs.showWarnings", true)
                );
    }

    void store() {
        NbPreferences.forModule(CodeSniffer.class).put(
                "phpcs.codingStandard",
                this.inputBoxStandard.getSelectedItem().toString()
                );

        NbPreferences.forModule(CodeSniffer.class).putBoolean(
                "phpcs.showWarnings",
                this.checkBoxShowWarnings.isSelected()
                );

        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());

    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxShowWarnings;
    private javax.swing.JComboBox inputBoxStandard;
    private javax.swing.JLabel labelStandard;
    // End of variables declaration//GEN-END:variables
}
